<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyTour" Class="QuanLyTourDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-3T163PO\SQLEXPRESS;Initial Catalog=QuanLyTour;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyTourConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TOURDULICH" Member="TOURDULICHes">
    <Type Name="TOURDULICH">
      <Column Name="MaTour" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGoi" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DacDiem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiHinh" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="TOURDULICH_DOANDULICH" Member="DOANDULICHes" ThisKey="MaTour" OtherKey="MaTour" Type="DOANDULICH" />
      <Association Name="TOURDULICH_GIATOUR" Member="GIATOURs" ThisKey="MaTour" OtherKey="MaTour" Type="GIATOUR" />
      <Association Name="TOURDULICH_THAMQUAN" Member="THAMQUANs" ThisKey="MaTour" OtherKey="MaTour" Type="THAMQUAN" />
      <Association Name="LOAIHINHDULICH_TOURDULICH" Member="LOAIHINHDULICH" ThisKey="MaLoaiHinh" OtherKey="MaLoaiHinh" Type="LOAIHINHDULICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHIPHI" Member="CHIPHIs">
    <Type Name="CHIPHI">
      <Column Name="MaChiPhi" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDoan" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiChiPhi" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DOANDULICH_CHIPHI" Member="DOANDULICH" ThisKey="MaDoan" OtherKey="MaDoan" Type="DOANDULICH" IsForeignKey="true" />
      <Association Name="LOAICHIPHI_CHIPHI" Member="LOAICHIPHI" ThisKey="MaLoaiChiPhi" OtherKey="MaLoaiChiPhi" Type="LOAICHIPHI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDOAN" Member="CHITIETDOANs">
    <Type Name="CHITIETDOAN">
      <Column Name="MaDoan" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DOANDULICH_CHITIETDOAN" Member="DOANDULICH" ThisKey="MaDoan" OtherKey="MaDoan" Type="DOANDULICH" IsForeignKey="true" />
      <Association Name="KHACH_CHITIETDOAN" Member="KHACH" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KHACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIADIEM" Member="DIADIEMs">
    <Type Name="DIADIEM">
      <Column Name="MaDiaDiem" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDiaDiem" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="DIADIEM_THAMQUAN" Member="THAMQUANs" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="THAMQUAN" />
    </Type>
  </Table>
  <Table Name="dbo.DOANDULICH" Member="DOANDULICHes">
    <Type Name="DOANDULICH">
      <Column Name="MaDoan" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTour" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NgayKhoiHanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DOANDULICH_CHIPHI" Member="CHIPHIs" ThisKey="MaDoan" OtherKey="MaDoan" Type="CHIPHI" />
      <Association Name="DOANDULICH_CHITIETDOAN" Member="CHITIETDOANs" ThisKey="MaDoan" OtherKey="MaDoan" Type="CHITIETDOAN" />
      <Association Name="DOANDULICH_NOIDUNGTOUR" Member="NOIDUNGTOUR" ThisKey="MaDoan" OtherKey="MaDoan" Type="NOIDUNGTOUR" Cardinality="One" />
      <Association Name="DOANDULICH_PHANBONHANVIEN_DOAN" Member="PHANBONHANVIEN_DOANs" ThisKey="MaDoan" OtherKey="MaDoan" Type="PHANBONHANVIEN_DOAN" />
      <Association Name="TOURDULICH_DOANDULICH" Member="TOURDULICH" ThisKey="MaTour" OtherKey="MaTour" Type="TOURDULICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIATOUR" Member="GIATOURs">
    <Type Name="GIATOUR">
      <Column Name="MaGia" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTour" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TOURDULICH_GIATOUR" Member="TOURDULICH" ThisKey="MaTour" OtherKey="MaTour" Type="TOURDULICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACH" Member="KHACHes">
    <Type Name="KHACH">
      <Column Name="MaKhachHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="KHACH_CHITIETDOAN" Member="CHITIETDOANs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="CHITIETDOAN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAICHIPHI" Member="LOAICHIPHIs">
    <Type Name="LOAICHIPHI">
      <Column Name="MaLoaiChiPhi" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiChiPhi" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAICHIPHI_CHIPHI" Member="CHIPHIs" ThisKey="MaLoaiChiPhi" OtherKey="MaLoaiChiPhi" Type="CHIPHI" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHINHDULICH" Member="LOAIHINHDULICHes">
    <Type Name="LOAIHINHDULICH">
      <Column Name="MaLoaiHinh" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiHinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAIHINHDULICH_TOURDULICH" Member="TOURDULICHes" ThisKey="MaLoaiHinh" OtherKey="MaLoaiHinh" Type="TOURDULICH" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNhanVien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="NHANVIEN_PHANBONHANVIEN_DOAN" Member="PHANBONHANVIEN_DOANs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PHANBONHANVIEN_DOAN" />
    </Type>
  </Table>
  <Table Name="dbo.NOIDUNGTOUR" Member="NOIDUNGTOURs">
    <Type Name="NOIDUNGTOUR">
      <Column Name="MaDoan" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HanhTrinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="KhachSan" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DiaDiemThamQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DOANDULICH_NOIDUNGTOUR" Member="DOANDULICH" ThisKey="MaDoan" OtherKey="MaDoan" Type="DOANDULICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANBONHANVIEN_DOAN" Member="PHANBONHANVIEN_DOANs">
    <Type Name="PHANBONHANVIEN_DOAN">
      <Column Name="MaNhanVien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDoan" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NhiemVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DOANDULICH_PHANBONHANVIEN_DOAN" Member="DOANDULICH" ThisKey="MaDoan" OtherKey="MaDoan" Type="DOANDULICH" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHANBONHANVIEN_DOAN" Member="NHANVIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THAMQUAN" Member="THAMQUANs">
    <Type Name="THAMQUAN">
      <Column Name="MaTour" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDiaDiem" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThuTu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DIADIEM_THAMQUAN" Member="DIADIEM" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="DIADIEM" IsForeignKey="true" />
      <Association Name="TOURDULICH_THAMQUAN" Member="TOURDULICH" ThisKey="MaTour" OtherKey="MaTour" Type="TOURDULICH" IsForeignKey="true" />
    </Type>
  </Table>
</Database>