#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyTour")]
	public partial class QuanLyTourDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHIPHI(CHIPHI instance);
    partial void UpdateCHIPHI(CHIPHI instance);
    partial void DeleteCHIPHI(CHIPHI instance);
    partial void InsertTOURDULICH(TOURDULICH instance);
    partial void UpdateTOURDULICH(TOURDULICH instance);
    partial void DeleteTOURDULICH(TOURDULICH instance);
    partial void InsertCHITIETDOAN(CHITIETDOAN instance);
    partial void UpdateCHITIETDOAN(CHITIETDOAN instance);
    partial void DeleteCHITIETDOAN(CHITIETDOAN instance);
    partial void InsertDIADIEM(DIADIEM instance);
    partial void UpdateDIADIEM(DIADIEM instance);
    partial void DeleteDIADIEM(DIADIEM instance);
    partial void InsertDOANDULICH(DOANDULICH instance);
    partial void UpdateDOANDULICH(DOANDULICH instance);
    partial void DeleteDOANDULICH(DOANDULICH instance);
    partial void InsertGIATOUR(GIATOUR instance);
    partial void UpdateGIATOUR(GIATOUR instance);
    partial void DeleteGIATOUR(GIATOUR instance);
    partial void InsertKHACH(KHACH instance);
    partial void UpdateKHACH(KHACH instance);
    partial void DeleteKHACH(KHACH instance);
    partial void InsertLOAICHIPHI(LOAICHIPHI instance);
    partial void UpdateLOAICHIPHI(LOAICHIPHI instance);
    partial void DeleteLOAICHIPHI(LOAICHIPHI instance);
    partial void InsertLOAIHINHDULICH(LOAIHINHDULICH instance);
    partial void UpdateLOAIHINHDULICH(LOAIHINHDULICH instance);
    partial void DeleteLOAIHINHDULICH(LOAIHINHDULICH instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNOIDUNGTOUR(NOIDUNGTOUR instance);
    partial void UpdateNOIDUNGTOUR(NOIDUNGTOUR instance);
    partial void DeleteNOIDUNGTOUR(NOIDUNGTOUR instance);
    partial void InsertPHANBONHANVIEN_DOAN(PHANBONHANVIEN_DOAN instance);
    partial void UpdatePHANBONHANVIEN_DOAN(PHANBONHANVIEN_DOAN instance);
    partial void DeletePHANBONHANVIEN_DOAN(PHANBONHANVIEN_DOAN instance);
    partial void InsertTHAMQUAN(THAMQUAN instance);
    partial void UpdateTHAMQUAN(THAMQUAN instance);
    partial void DeleteTHAMQUAN(THAMQUAN instance);
    #endregion
		
		public QuanLyTourDataContext() : 
				base(global::Backend.Properties.Settings.Default.QuanLyTourConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHIPHI> CHIPHIs
		{
			get
			{
				return this.GetTable<CHIPHI>();
			}
		}
		
		public System.Data.Linq.Table<TOURDULICH> TOURDULICHes
		{
			get
			{
				return this.GetTable<TOURDULICH>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDOAN> CHITIETDOANs
		{
			get
			{
				return this.GetTable<CHITIETDOAN>();
			}
		}
		
		public System.Data.Linq.Table<DIADIEM> DIADIEMs
		{
			get
			{
				return this.GetTable<DIADIEM>();
			}
		}
		
		public System.Data.Linq.Table<DOANDULICH> DOANDULICHes
		{
			get
			{
				return this.GetTable<DOANDULICH>();
			}
		}
		
		public System.Data.Linq.Table<GIATOUR> GIATOURs
		{
			get
			{
				return this.GetTable<GIATOUR>();
			}
		}
		
		public System.Data.Linq.Table<KHACH> KHACHes
		{
			get
			{
				return this.GetTable<KHACH>();
			}
		}
		
		public System.Data.Linq.Table<LOAICHIPHI> LOAICHIPHIs
		{
			get
			{
				return this.GetTable<LOAICHIPHI>();
			}
		}
		
		public System.Data.Linq.Table<LOAIHINHDULICH> LOAIHINHDULICHes
		{
			get
			{
				return this.GetTable<LOAIHINHDULICH>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NOIDUNGTOUR> NOIDUNGTOURs
		{
			get
			{
				return this.GetTable<NOIDUNGTOUR>();
			}
		}
		
		public System.Data.Linq.Table<PHANBONHANVIEN_DOAN> PHANBONHANVIEN_DOANs
		{
			get
			{
				return this.GetTable<PHANBONHANVIEN_DOAN>();
			}
		}
		
		public System.Data.Linq.Table<THAMQUAN> THAMQUANs
		{
			get
			{
				return this.GetTable<THAMQUAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHIPHI")]
	public partial class CHIPHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChiPhi;
		
		private string _MaDoan;
		
		private System.Nullable<int> _SoTien;
		
		private string _MaLoaiChiPhi;
		
		private EntityRef<DOANDULICH> _DOANDULICH;
		
		private EntityRef<LOAICHIPHI> _LOAICHIPHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiPhiChanging(string value);
    partial void OnMaChiPhiChanged();
    partial void OnMaDoanChanging(string value);
    partial void OnMaDoanChanged();
    partial void OnSoTienChanging(System.Nullable<int> value);
    partial void OnSoTienChanged();
    partial void OnMaLoaiChiPhiChanging(string value);
    partial void OnMaLoaiChiPhiChanged();
    #endregion
		
		public CHIPHI()
		{
			this._DOANDULICH = default(EntityRef<DOANDULICH>);
			this._LOAICHIPHI = default(EntityRef<LOAICHIPHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiPhi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChiPhi
		{
			get
			{
				return this._MaChiPhi;
			}
			set
			{
				if ((this._MaChiPhi != value))
				{
					this.OnMaChiPhiChanging(value);
					this.SendPropertyChanging();
					this._MaChiPhi = value;
					this.SendPropertyChanged("MaChiPhi");
					this.OnMaChiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoan", DbType="Char(10)")]
		public string MaDoan
		{
			get
			{
				return this._MaDoan;
			}
			set
			{
				if ((this._MaDoan != value))
				{
					if (this._DOANDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoanChanging(value);
					this.SendPropertyChanging();
					this._MaDoan = value;
					this.SendPropertyChanged("MaDoan");
					this.OnMaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Int")]
		public System.Nullable<int> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiChiPhi", DbType="Char(10)")]
		public string MaLoaiChiPhi
		{
			get
			{
				return this._MaLoaiChiPhi;
			}
			set
			{
				if ((this._MaLoaiChiPhi != value))
				{
					if (this._LOAICHIPHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChiPhiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiChiPhi = value;
					this.SendPropertyChanged("MaLoaiChiPhi");
					this.OnMaLoaiChiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_CHIPHI", Storage="_DOANDULICH", ThisKey="MaDoan", OtherKey="MaDoan", IsForeignKey=true)]
		public DOANDULICH DOANDULICH
		{
			get
			{
				return this._DOANDULICH.Entity;
			}
			set
			{
				DOANDULICH previousValue = this._DOANDULICH.Entity;
				if (((previousValue != value) 
							|| (this._DOANDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOANDULICH.Entity = null;
						previousValue.CHIPHIs.Remove(this);
					}
					this._DOANDULICH.Entity = value;
					if ((value != null))
					{
						value.CHIPHIs.Add(this);
						this._MaDoan = value.MaDoan;
					}
					else
					{
						this._MaDoan = default(string);
					}
					this.SendPropertyChanged("DOANDULICH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICHIPHI_CHIPHI", Storage="_LOAICHIPHI", ThisKey="MaLoaiChiPhi", OtherKey="MaLoaiChiPhi", IsForeignKey=true)]
		public LOAICHIPHI LOAICHIPHI
		{
			get
			{
				return this._LOAICHIPHI.Entity;
			}
			set
			{
				LOAICHIPHI previousValue = this._LOAICHIPHI.Entity;
				if (((previousValue != value) 
							|| (this._LOAICHIPHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAICHIPHI.Entity = null;
						previousValue.CHIPHIs.Remove(this);
					}
					this._LOAICHIPHI.Entity = value;
					if ((value != null))
					{
						value.CHIPHIs.Add(this);
						this._MaLoaiChiPhi = value.MaLoaiChiPhi;
					}
					else
					{
						this._MaLoaiChiPhi = default(string);
					}
					this.SendPropertyChanged("LOAICHIPHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOURDULICH")]
	public partial class TOURDULICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTour;
		
		private string _TenGoi;
		
		private string _DacDiem;
		
		private string _MaLoaiHinh;
		
		private EntitySet<DOANDULICH> _DOANDULICHes;
		
		private EntitySet<GIATOUR> _GIATOURs;
		
		private EntitySet<THAMQUAN> _THAMQUANs;
		
		private EntityRef<LOAIHINHDULICH> _LOAIHINHDULICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnTenGoiChanging(string value);
    partial void OnTenGoiChanged();
    partial void OnDacDiemChanging(string value);
    partial void OnDacDiemChanged();
    partial void OnMaLoaiHinhChanging(string value);
    partial void OnMaLoaiHinhChanged();
    #endregion
		
		public TOURDULICH()
		{
			this._DOANDULICHes = new EntitySet<DOANDULICH>(new Action<DOANDULICH>(this.attach_DOANDULICHes), new Action<DOANDULICH>(this.detach_DOANDULICHes));
			this._GIATOURs = new EntitySet<GIATOUR>(new Action<GIATOUR>(this.attach_GIATOURs), new Action<GIATOUR>(this.detach_GIATOURs));
			this._THAMQUANs = new EntitySet<THAMQUAN>(new Action<THAMQUAN>(this.attach_THAMQUANs), new Action<THAMQUAN>(this.detach_THAMQUANs));
			this._LOAIHINHDULICH = default(EntityRef<LOAIHINHDULICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGoi", DbType="NVarChar(20)")]
		public string TenGoi
		{
			get
			{
				return this._TenGoi;
			}
			set
			{
				if ((this._TenGoi != value))
				{
					this.OnTenGoiChanging(value);
					this.SendPropertyChanging();
					this._TenGoi = value;
					this.SendPropertyChanged("TenGoi");
					this.OnTenGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DacDiem", DbType="NVarChar(50)")]
		public string DacDiem
		{
			get
			{
				return this._DacDiem;
			}
			set
			{
				if ((this._DacDiem != value))
				{
					this.OnDacDiemChanging(value);
					this.SendPropertyChanging();
					this._DacDiem = value;
					this.SendPropertyChanged("DacDiem");
					this.OnDacDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHinh", DbType="Char(10)")]
		public string MaLoaiHinh
		{
			get
			{
				return this._MaLoaiHinh;
			}
			set
			{
				if ((this._MaLoaiHinh != value))
				{
					if (this._LOAIHINHDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiHinhChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHinh = value;
					this.SendPropertyChanged("MaLoaiHinh");
					this.OnMaLoaiHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOURDULICH_DOANDULICH", Storage="_DOANDULICHes", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<DOANDULICH> DOANDULICHes
		{
			get
			{
				return this._DOANDULICHes;
			}
			set
			{
				this._DOANDULICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOURDULICH_GIATOUR", Storage="_GIATOURs", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<GIATOUR> GIATOURs
		{
			get
			{
				return this._GIATOURs;
			}
			set
			{
				this._GIATOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOURDULICH_THAMQUAN", Storage="_THAMQUANs", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<THAMQUAN> THAMQUANs
		{
			get
			{
				return this._THAMQUANs;
			}
			set
			{
				this._THAMQUANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHINHDULICH_TOURDULICH", Storage="_LOAIHINHDULICH", ThisKey="MaLoaiHinh", OtherKey="MaLoaiHinh", IsForeignKey=true)]
		public LOAIHINHDULICH LOAIHINHDULICH
		{
			get
			{
				return this._LOAIHINHDULICH.Entity;
			}
			set
			{
				LOAIHINHDULICH previousValue = this._LOAIHINHDULICH.Entity;
				if (((previousValue != value) 
							|| (this._LOAIHINHDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIHINHDULICH.Entity = null;
						previousValue.TOURDULICHes.Remove(this);
					}
					this._LOAIHINHDULICH.Entity = value;
					if ((value != null))
					{
						value.TOURDULICHes.Add(this);
						this._MaLoaiHinh = value.MaLoaiHinh;
					}
					else
					{
						this._MaLoaiHinh = default(string);
					}
					this.SendPropertyChanged("LOAIHINHDULICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DOANDULICHes(DOANDULICH entity)
		{
			this.SendPropertyChanging();
			entity.TOURDULICH = this;
		}
		
		private void detach_DOANDULICHes(DOANDULICH entity)
		{
			this.SendPropertyChanging();
			entity.TOURDULICH = null;
		}
		
		private void attach_GIATOURs(GIATOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDULICH = this;
		}
		
		private void detach_GIATOURs(GIATOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDULICH = null;
		}
		
		private void attach_THAMQUANs(THAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.TOURDULICH = this;
		}
		
		private void detach_THAMQUANs(THAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.TOURDULICH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDOAN")]
	public partial class CHITIETDOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoan;
		
		private string _MaKhachHang;
		
		private EntityRef<DOANDULICH> _DOANDULICH;
		
		private EntityRef<KHACH> _KHACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoanChanging(string value);
    partial void OnMaDoanChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    #endregion
		
		public CHITIETDOAN()
		{
			this._DOANDULICH = default(EntityRef<DOANDULICH>);
			this._KHACH = default(EntityRef<KHACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoan
		{
			get
			{
				return this._MaDoan;
			}
			set
			{
				if ((this._MaDoan != value))
				{
					if (this._DOANDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoanChanging(value);
					this.SendPropertyChanging();
					this._MaDoan = value;
					this.SendPropertyChanged("MaDoan");
					this.OnMaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_CHITIETDOAN", Storage="_DOANDULICH", ThisKey="MaDoan", OtherKey="MaDoan", IsForeignKey=true)]
		public DOANDULICH DOANDULICH
		{
			get
			{
				return this._DOANDULICH.Entity;
			}
			set
			{
				DOANDULICH previousValue = this._DOANDULICH.Entity;
				if (((previousValue != value) 
							|| (this._DOANDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOANDULICH.Entity = null;
						previousValue.CHITIETDOANs.Remove(this);
					}
					this._DOANDULICH.Entity = value;
					if ((value != null))
					{
						value.CHITIETDOANs.Add(this);
						this._MaDoan = value.MaDoan;
					}
					else
					{
						this._MaDoan = default(string);
					}
					this.SendPropertyChanged("DOANDULICH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_CHITIETDOAN", Storage="_KHACH", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH KHACH
		{
			get
			{
				return this._KHACH.Entity;
			}
			set
			{
				KHACH previousValue = this._KHACH.Entity;
				if (((previousValue != value) 
							|| (this._KHACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH.Entity = null;
						previousValue.CHITIETDOANs.Remove(this);
					}
					this._KHACH.Entity = value;
					if ((value != null))
					{
						value.CHITIETDOANs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIADIEM")]
	public partial class DIADIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDiaDiem;
		
		private string _TenDiaDiem;
		
		private EntitySet<THAMQUAN> _THAMQUANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaDiemChanging(string value);
    partial void OnMaDiaDiemChanged();
    partial void OnTenDiaDiemChanging(string value);
    partial void OnTenDiaDiemChanged();
    #endregion
		
		public DIADIEM()
		{
			this._THAMQUANs = new EntitySet<THAMQUAN>(new Action<THAMQUAN>(this.attach_THAMQUANs), new Action<THAMQUAN>(this.detach_THAMQUANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDiem", DbType="NVarChar(20)")]
		public string TenDiaDiem
		{
			get
			{
				return this._TenDiaDiem;
			}
			set
			{
				if ((this._TenDiaDiem != value))
				{
					this.OnTenDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDiem = value;
					this.SendPropertyChanged("TenDiaDiem");
					this.OnTenDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_THAMQUAN", Storage="_THAMQUANs", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem")]
		public EntitySet<THAMQUAN> THAMQUANs
		{
			get
			{
				return this._THAMQUANs;
			}
			set
			{
				this._THAMQUANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THAMQUANs(THAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = this;
		}
		
		private void detach_THAMQUANs(THAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOANDULICH")]
	public partial class DOANDULICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoan;
		
		private string _MaTour;
		
		private System.Nullable<System.DateTime> _NgayKhoiHanh;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private EntitySet<CHIPHI> _CHIPHIs;
		
		private EntitySet<CHITIETDOAN> _CHITIETDOANs;
		
		private EntityRef<NOIDUNGTOUR> _NOIDUNGTOUR;
		
		private EntitySet<PHANBONHANVIEN_DOAN> _PHANBONHANVIEN_DOANs;
		
		private EntityRef<TOURDULICH> _TOURDULICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoanChanging(string value);
    partial void OnMaDoanChanged();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnNgayKhoiHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhoiHanhChanged();
    partial void OnNgayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucChanged();
    #endregion
		
		public DOANDULICH()
		{
			this._CHIPHIs = new EntitySet<CHIPHI>(new Action<CHIPHI>(this.attach_CHIPHIs), new Action<CHIPHI>(this.detach_CHIPHIs));
			this._CHITIETDOANs = new EntitySet<CHITIETDOAN>(new Action<CHITIETDOAN>(this.attach_CHITIETDOANs), new Action<CHITIETDOAN>(this.detach_CHITIETDOANs));
			this._NOIDUNGTOUR = default(EntityRef<NOIDUNGTOUR>);
			this._PHANBONHANVIEN_DOANs = new EntitySet<PHANBONHANVIEN_DOAN>(new Action<PHANBONHANVIEN_DOAN>(this.attach_PHANBONHANVIEN_DOANs), new Action<PHANBONHANVIEN_DOAN>(this.detach_PHANBONHANVIEN_DOANs));
			this._TOURDULICH = default(EntityRef<TOURDULICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoan
		{
			get
			{
				return this._MaDoan;
			}
			set
			{
				if ((this._MaDoan != value))
				{
					this.OnMaDoanChanging(value);
					this.SendPropertyChanging();
					this._MaDoan = value;
					this.SendPropertyChanged("MaDoan");
					this.OnMaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Char(10)")]
		public string MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._TOURDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiHanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKhoiHanh
		{
			get
			{
				return this._NgayKhoiHanh;
			}
			set
			{
				if ((this._NgayKhoiHanh != value))
				{
					this.OnNgayKhoiHanhChanging(value);
					this.SendPropertyChanging();
					this._NgayKhoiHanh = value;
					this.SendPropertyChanged("NgayKhoiHanh");
					this.OnNgayKhoiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_CHIPHI", Storage="_CHIPHIs", ThisKey="MaDoan", OtherKey="MaDoan")]
		public EntitySet<CHIPHI> CHIPHIs
		{
			get
			{
				return this._CHIPHIs;
			}
			set
			{
				this._CHIPHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_CHITIETDOAN", Storage="_CHITIETDOANs", ThisKey="MaDoan", OtherKey="MaDoan")]
		public EntitySet<CHITIETDOAN> CHITIETDOANs
		{
			get
			{
				return this._CHITIETDOANs;
			}
			set
			{
				this._CHITIETDOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_NOIDUNGTOUR", Storage="_NOIDUNGTOUR", ThisKey="MaDoan", OtherKey="MaDoan", IsUnique=true, IsForeignKey=false)]
		public NOIDUNGTOUR NOIDUNGTOUR
		{
			get
			{
				return this._NOIDUNGTOUR.Entity;
			}
			set
			{
				NOIDUNGTOUR previousValue = this._NOIDUNGTOUR.Entity;
				if (((previousValue != value) 
							|| (this._NOIDUNGTOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NOIDUNGTOUR.Entity = null;
						previousValue.DOANDULICH = null;
					}
					this._NOIDUNGTOUR.Entity = value;
					if ((value != null))
					{
						value.DOANDULICH = this;
					}
					this.SendPropertyChanged("NOIDUNGTOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_PHANBONHANVIEN_DOAN", Storage="_PHANBONHANVIEN_DOANs", ThisKey="MaDoan", OtherKey="MaDoan")]
		public EntitySet<PHANBONHANVIEN_DOAN> PHANBONHANVIEN_DOANs
		{
			get
			{
				return this._PHANBONHANVIEN_DOANs;
			}
			set
			{
				this._PHANBONHANVIEN_DOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOURDULICH_DOANDULICH", Storage="_TOURDULICH", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public TOURDULICH TOURDULICH
		{
			get
			{
				return this._TOURDULICH.Entity;
			}
			set
			{
				TOURDULICH previousValue = this._TOURDULICH.Entity;
				if (((previousValue != value) 
							|| (this._TOURDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOURDULICH.Entity = null;
						previousValue.DOANDULICHes.Remove(this);
					}
					this._TOURDULICH.Entity = value;
					if ((value != null))
					{
						value.DOANDULICHes.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(string);
					}
					this.SendPropertyChanged("TOURDULICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHIPHIs(CHIPHI entity)
		{
			this.SendPropertyChanging();
			entity.DOANDULICH = this;
		}
		
		private void detach_CHIPHIs(CHIPHI entity)
		{
			this.SendPropertyChanging();
			entity.DOANDULICH = null;
		}
		
		private void attach_CHITIETDOANs(CHITIETDOAN entity)
		{
			this.SendPropertyChanging();
			entity.DOANDULICH = this;
		}
		
		private void detach_CHITIETDOANs(CHITIETDOAN entity)
		{
			this.SendPropertyChanging();
			entity.DOANDULICH = null;
		}
		
		private void attach_PHANBONHANVIEN_DOANs(PHANBONHANVIEN_DOAN entity)
		{
			this.SendPropertyChanging();
			entity.DOANDULICH = this;
		}
		
		private void detach_PHANBONHANVIEN_DOANs(PHANBONHANVIEN_DOAN entity)
		{
			this.SendPropertyChanging();
			entity.DOANDULICH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIATOUR")]
	public partial class GIATOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGia;
		
		private string _MaTour;
		
		private System.Nullable<int> _ThanhTien;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private EntityRef<TOURDULICH> _TOURDULICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaChanging(string value);
    partial void OnMaGiaChanged();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    #endregion
		
		public GIATOUR()
		{
			this._TOURDULICH = default(EntityRef<TOURDULICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGia", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGia
		{
			get
			{
				return this._MaGia;
			}
			set
			{
				if ((this._MaGia != value))
				{
					this.OnMaGiaChanging(value);
					this.SendPropertyChanging();
					this._MaGia = value;
					this.SendPropertyChanged("MaGia");
					this.OnMaGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Char(10)")]
		public string MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._TOURDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOURDULICH_GIATOUR", Storage="_TOURDULICH", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public TOURDULICH TOURDULICH
		{
			get
			{
				return this._TOURDULICH.Entity;
			}
			set
			{
				TOURDULICH previousValue = this._TOURDULICH.Entity;
				if (((previousValue != value) 
							|| (this._TOURDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOURDULICH.Entity = null;
						previousValue.GIATOURs.Remove(this);
					}
					this._TOURDULICH.Entity = value;
					if ((value != null))
					{
						value.GIATOURs.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(string);
					}
					this.SendPropertyChanged("TOURDULICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH")]
	public partial class KHACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _HoTen;
		
		private string _SoCMND;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _QuocTich;
		
		private EntitySet<CHITIETDOAN> _CHITIETDOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    #endregion
		
		public KHACH()
		{
			this._CHITIETDOANs = new EntitySet<CHITIETDOAN>(new Action<CHITIETDOAN>(this.attach_CHITIETDOANs), new Action<CHITIETDOAN>(this.detach_CHITIETDOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(20)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="Char(10)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(20)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_CHITIETDOAN", Storage="_CHITIETDOANs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<CHITIETDOAN> CHITIETDOANs
		{
			get
			{
				return this._CHITIETDOANs;
			}
			set
			{
				this._CHITIETDOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDOANs(CHITIETDOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = this;
		}
		
		private void detach_CHITIETDOANs(CHITIETDOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAICHIPHI")]
	public partial class LOAICHIPHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiChiPhi;
		
		private string _TenLoaiChiPhi;
		
		private EntitySet<CHIPHI> _CHIPHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChiPhiChanging(string value);
    partial void OnMaLoaiChiPhiChanged();
    partial void OnTenLoaiChiPhiChanging(string value);
    partial void OnTenLoaiChiPhiChanged();
    #endregion
		
		public LOAICHIPHI()
		{
			this._CHIPHIs = new EntitySet<CHIPHI>(new Action<CHIPHI>(this.attach_CHIPHIs), new Action<CHIPHI>(this.detach_CHIPHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiChiPhi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiChiPhi
		{
			get
			{
				return this._MaLoaiChiPhi;
			}
			set
			{
				if ((this._MaLoaiChiPhi != value))
				{
					this.OnMaLoaiChiPhiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiChiPhi = value;
					this.SendPropertyChanged("MaLoaiChiPhi");
					this.OnMaLoaiChiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiChiPhi", DbType="NVarChar(20)")]
		public string TenLoaiChiPhi
		{
			get
			{
				return this._TenLoaiChiPhi;
			}
			set
			{
				if ((this._TenLoaiChiPhi != value))
				{
					this.OnTenLoaiChiPhiChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiChiPhi = value;
					this.SendPropertyChanged("TenLoaiChiPhi");
					this.OnTenLoaiChiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICHIPHI_CHIPHI", Storage="_CHIPHIs", ThisKey="MaLoaiChiPhi", OtherKey="MaLoaiChiPhi")]
		public EntitySet<CHIPHI> CHIPHIs
		{
			get
			{
				return this._CHIPHIs;
			}
			set
			{
				this._CHIPHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHIPHIs(CHIPHI entity)
		{
			this.SendPropertyChanging();
			entity.LOAICHIPHI = this;
		}
		
		private void detach_CHIPHIs(CHIPHI entity)
		{
			this.SendPropertyChanging();
			entity.LOAICHIPHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHINHDULICH")]
	public partial class LOAIHINHDULICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiHinh;
		
		private string _TenLoaiHinh;
		
		private EntitySet<TOURDULICH> _TOURDULICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiHinhChanging(string value);
    partial void OnMaLoaiHinhChanged();
    partial void OnTenLoaiHinhChanging(string value);
    partial void OnTenLoaiHinhChanged();
    #endregion
		
		public LOAIHINHDULICH()
		{
			this._TOURDULICHes = new EntitySet<TOURDULICH>(new Action<TOURDULICH>(this.attach_TOURDULICHes), new Action<TOURDULICH>(this.detach_TOURDULICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHinh", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiHinh
		{
			get
			{
				return this._MaLoaiHinh;
			}
			set
			{
				if ((this._MaLoaiHinh != value))
				{
					this.OnMaLoaiHinhChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHinh = value;
					this.SendPropertyChanged("MaLoaiHinh");
					this.OnMaLoaiHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiHinh", DbType="NVarChar(20)")]
		public string TenLoaiHinh
		{
			get
			{
				return this._TenLoaiHinh;
			}
			set
			{
				if ((this._TenLoaiHinh != value))
				{
					this.OnTenLoaiHinhChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiHinh = value;
					this.SendPropertyChanged("TenLoaiHinh");
					this.OnTenLoaiHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHINHDULICH_TOURDULICH", Storage="_TOURDULICHes", ThisKey="MaLoaiHinh", OtherKey="MaLoaiHinh")]
		public EntitySet<TOURDULICH> TOURDULICHes
		{
			get
			{
				return this._TOURDULICHes;
			}
			set
			{
				this._TOURDULICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURDULICHes(TOURDULICH entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHINHDULICH = this;
		}
		
		private void detach_TOURDULICHes(TOURDULICH entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHINHDULICH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenNhanVien;
		
		private EntitySet<PHANBONHANVIEN_DOAN> _PHANBONHANVIEN_DOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHANBONHANVIEN_DOANs = new EntitySet<PHANBONHANVIEN_DOAN>(new Action<PHANBONHANVIEN_DOAN>(this.attach_PHANBONHANVIEN_DOANs), new Action<PHANBONHANVIEN_DOAN>(this.detach_PHANBONHANVIEN_DOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(20)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHANBONHANVIEN_DOAN", Storage="_PHANBONHANVIEN_DOANs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<PHANBONHANVIEN_DOAN> PHANBONHANVIEN_DOANs
		{
			get
			{
				return this._PHANBONHANVIEN_DOANs;
			}
			set
			{
				this._PHANBONHANVIEN_DOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANBONHANVIEN_DOANs(PHANBONHANVIEN_DOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHANBONHANVIEN_DOANs(PHANBONHANVIEN_DOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDUNGTOUR")]
	public partial class NOIDUNGTOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoan;
		
		private string _HanhTrinh;
		
		private string _KhachSan;
		
		private string _DiaDiemThamQuan;
		
		private EntityRef<DOANDULICH> _DOANDULICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoanChanging(string value);
    partial void OnMaDoanChanged();
    partial void OnHanhTrinhChanging(string value);
    partial void OnHanhTrinhChanged();
    partial void OnKhachSanChanging(string value);
    partial void OnKhachSanChanged();
    partial void OnDiaDiemThamQuanChanging(string value);
    partial void OnDiaDiemThamQuanChanged();
    #endregion
		
		public NOIDUNGTOUR()
		{
			this._DOANDULICH = default(EntityRef<DOANDULICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoan
		{
			get
			{
				return this._MaDoan;
			}
			set
			{
				if ((this._MaDoan != value))
				{
					if (this._DOANDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoanChanging(value);
					this.SendPropertyChanging();
					this._MaDoan = value;
					this.SendPropertyChanged("MaDoan");
					this.OnMaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanhTrinh", DbType="NVarChar(20)")]
		public string HanhTrinh
		{
			get
			{
				return this._HanhTrinh;
			}
			set
			{
				if ((this._HanhTrinh != value))
				{
					this.OnHanhTrinhChanging(value);
					this.SendPropertyChanging();
					this._HanhTrinh = value;
					this.SendPropertyChanged("HanhTrinh");
					this.OnHanhTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachSan", DbType="NVarChar(20)")]
		public string KhachSan
		{
			get
			{
				return this._KhachSan;
			}
			set
			{
				if ((this._KhachSan != value))
				{
					this.OnKhachSanChanging(value);
					this.SendPropertyChanging();
					this._KhachSan = value;
					this.SendPropertyChanged("KhachSan");
					this.OnKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemThamQuan", DbType="NVarChar(50)")]
		public string DiaDiemThamQuan
		{
			get
			{
				return this._DiaDiemThamQuan;
			}
			set
			{
				if ((this._DiaDiemThamQuan != value))
				{
					this.OnDiaDiemThamQuanChanging(value);
					this.SendPropertyChanging();
					this._DiaDiemThamQuan = value;
					this.SendPropertyChanged("DiaDiemThamQuan");
					this.OnDiaDiemThamQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_NOIDUNGTOUR", Storage="_DOANDULICH", ThisKey="MaDoan", OtherKey="MaDoan", IsForeignKey=true)]
		public DOANDULICH DOANDULICH
		{
			get
			{
				return this._DOANDULICH.Entity;
			}
			set
			{
				DOANDULICH previousValue = this._DOANDULICH.Entity;
				if (((previousValue != value) 
							|| (this._DOANDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOANDULICH.Entity = null;
						previousValue.NOIDUNGTOUR = null;
					}
					this._DOANDULICH.Entity = value;
					if ((value != null))
					{
						value.NOIDUNGTOUR = this;
						this._MaDoan = value.MaDoan;
					}
					else
					{
						this._MaDoan = default(string);
					}
					this.SendPropertyChanged("DOANDULICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANBONHANVIEN_DOAN")]
	public partial class PHANBONHANVIEN_DOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _MaDoan;
		
		private string _NhiemVu;
		
		private EntityRef<DOANDULICH> _DOANDULICH;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnMaDoanChanging(string value);
    partial void OnMaDoanChanged();
    partial void OnNhiemVuChanging(string value);
    partial void OnNhiemVuChanged();
    #endregion
		
		public PHANBONHANVIEN_DOAN()
		{
			this._DOANDULICH = default(EntityRef<DOANDULICH>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoan
		{
			get
			{
				return this._MaDoan;
			}
			set
			{
				if ((this._MaDoan != value))
				{
					if (this._DOANDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoanChanging(value);
					this.SendPropertyChanging();
					this._MaDoan = value;
					this.SendPropertyChanged("MaDoan");
					this.OnMaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhiemVu", DbType="NVarChar(50)")]
		public string NhiemVu
		{
			get
			{
				return this._NhiemVu;
			}
			set
			{
				if ((this._NhiemVu != value))
				{
					this.OnNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._NhiemVu = value;
					this.SendPropertyChanged("NhiemVu");
					this.OnNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANDULICH_PHANBONHANVIEN_DOAN", Storage="_DOANDULICH", ThisKey="MaDoan", OtherKey="MaDoan", IsForeignKey=true)]
		public DOANDULICH DOANDULICH
		{
			get
			{
				return this._DOANDULICH.Entity;
			}
			set
			{
				DOANDULICH previousValue = this._DOANDULICH.Entity;
				if (((previousValue != value) 
							|| (this._DOANDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOANDULICH.Entity = null;
						previousValue.PHANBONHANVIEN_DOANs.Remove(this);
					}
					this._DOANDULICH.Entity = value;
					if ((value != null))
					{
						value.PHANBONHANVIEN_DOANs.Add(this);
						this._MaDoan = value.MaDoan;
					}
					else
					{
						this._MaDoan = default(string);
					}
					this.SendPropertyChanged("DOANDULICH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHANBONHANVIEN_DOAN", Storage="_NHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHANBONHANVIEN_DOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHANBONHANVIEN_DOANs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THAMQUAN")]
	public partial class THAMQUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTour;
		
		private string _MaDiaDiem;
		
		private int _ThuTu;
		
		private EntityRef<DIADIEM> _DIADIEM;
		
		private EntityRef<TOURDULICH> _TOURDULICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnMaDiaDiemChanging(string value);
    partial void OnMaDiaDiemChanged();
    partial void OnThuTuChanging(int value);
    partial void OnThuTuChanged();
    #endregion
		
		public THAMQUAN()
		{
			this._DIADIEM = default(EntityRef<DIADIEM>);
			this._TOURDULICH = default(EntityRef<TOURDULICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._TOURDULICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					if (this._DIADIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_THAMQUAN", Storage="_DIADIEM", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DIADIEM DIADIEM
		{
			get
			{
				return this._DIADIEM.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM.Entity;
				if (((previousValue != value) 
							|| (this._DIADIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM.Entity = null;
						previousValue.THAMQUANs.Remove(this);
					}
					this._DIADIEM.Entity = value;
					if ((value != null))
					{
						value.THAMQUANs.Add(this);
						this._MaDiaDiem = value.MaDiaDiem;
					}
					else
					{
						this._MaDiaDiem = default(string);
					}
					this.SendPropertyChanged("DIADIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOURDULICH_THAMQUAN", Storage="_TOURDULICH", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public TOURDULICH TOURDULICH
		{
			get
			{
				return this._TOURDULICH.Entity;
			}
			set
			{
				TOURDULICH previousValue = this._TOURDULICH.Entity;
				if (((previousValue != value) 
							|| (this._TOURDULICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOURDULICH.Entity = null;
						previousValue.THAMQUANs.Remove(this);
					}
					this._TOURDULICH.Entity = value;
					if ((value != null))
					{
						value.THAMQUANs.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(string);
					}
					this.SendPropertyChanged("TOURDULICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
