//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIPHI
    {
        public string MaChiPhi { get; set; }
        public string MaDoan { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string MaLoaiChiPhi { get; set; }
    
        public virtual DOANDULICH DOANDULICH { get; set; }
        public virtual LOAICHIPHI LOAICHIPHI { get; set; }
    }
}
