//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTour
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTourEntities : DbContext
    {
        public QuanLyTourEntities()
            : base("name=QuanLyTourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHIPHI> CHIPHI { get; set; }
        public virtual DbSet<DIADIEM> DIADIEM { get; set; }
        public virtual DbSet<DOANDULICH> DOANDULICH { get; set; }
        public virtual DbSet<GIATOUR> GIATOUR { get; set; }
        public virtual DbSet<KHACH> KHACH { get; set; }
        public virtual DbSet<LOAICHIPHI> LOAICHIPHI { get; set; }
        public virtual DbSet<LOAIHINHDULICH> LOAIHINHDULICH { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<NOIDUNGTOUR> NOIDUNGTOUR { get; set; }
        public virtual DbSet<PHANBONHANVIEN_DOAN> PHANBONHANVIEN_DOAN { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<THAMQUAN> THAMQUAN { get; set; }
        public virtual DbSet<TOURDULICH> TOURDULICH { get; set; }
    }
}
